import type { Metadata } from 'next';
import React, { ReactNode } from 'react';
import './globals.css';
import Nav from '@/components/navigation/nav';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="de">
      <body className="antialiased mx-25">
        <header>
          <div className="flex justify-between bg-gray-800">
            <h1 className="text-white p-2">dmnkws.dev</h1>
            <Nav />
          </div>
        </header>
        {children}
        <footer>Footer</footer>
      </body>
    </html>
  );
}
